// Generated by tools/sync-plugins.js; edit plugin manifests then rerun the sync script.
export const BUILTIN_PLUGINS = [
  {
    "id": "shiguang-schedule",
    "name": "课程表",
    "version": "3.10.0",
    "author": "基于 XingHeYuZhuan/shiguangschedule · U-Time适配",
    "icon": "calendar-days",
    "faIcon": "calendar-days",
    "description": "将时光课程表嵌入 Le 时间管理；周视图一屏显示周一到周日全部节次（默认 10 节），手机端无边距铺满整屏，视图切换与常用操作收在右上角「⋯」菜单；支持选择学校并登录教务一键导入、教务 XLSX/XLS/CSV/TSV/HTML 导入、多课表、课程管理、彩色课程块（默认开）与个性化配置、JSON/ICS 备份及时间块联动。",
    "permissions": [
      "ui",
      "storage",
      "blocks",
      "notify",
      "http",
      "events",
      "schoolImport"
    ],
    "entry": "main.js",
    "order": 1,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "web-collector",
    "name": "网页收集",
    "version": "1.4.0",
    "author": "U-Time内置",
    "icon": "bookmark",
    "faIcon": "bookmark",
    "description": "输入网址或把浏览器标签、页面链接直接拖进本页，自动读取网站名称、favicon，并智能匹配 Font Awesome 图标；支持单独获取/更换网站图标、一次拖入多个网址、搜索、备注、刷新元信息和一键打开。",
    "permissions": [
      "ui",
      "storage",
      "notify",
      "http",
      "openUrl"
    ],
    "entry": "main.js",
    "order": 2,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "school-notice",
    "name": "学校通知网站",
    "version": "1.5.1",
    "author": "U-Time内置",
    "icon": "school",
    "faIcon": "school",
    "description": "输入学校公告/通知网址后自动识别常见高校 CMS 列表；对「服务端只吐空壳、列表靠 JS 渲染」的门户站点，命中已登记适配器时直接读取其数据接口。支持会话登录、用户名密码和手动验证码，并可把公告转成 U-Time提醒。站点菜单会始终显示网站名称；点击异站点先切换公告且默认收起设置卡片，再点当前站点才展开登录网址等设置；右键站点弹出操作菜单（刷新 / 登录配置 / 编辑 / 打开 / 删除）。抓到新公告时广播给微信推送插件，可在推送设置里单独勾选这个插件是否推送到微信。",
    "permissions": [
      "ui",
      "storage",
      "tasks",
      "blocks",
      "notify",
      "http",
      "openUrl",
      "timeParse",
      "events"
    ],
    "entry": "main.js",
    "order": 3,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "unavailable"
    }
  },
  {
    "id": "pomodoro",
    "name": "番茄专注",
    "version": "0.5.1",
    "author": "U-Time内置",
    "icon": "hourglass-half",
    "faIcon": "hourglass-half",
    "description": "环形番茄钟：挑一个任务开始专注，25 分钟后休息。自定义时长精确到秒，分 / 秒分开填（1 分 30 秒就是 1 分 30 秒，不必再写 1.5）。专注 / 休息结束可分别设置通知与提示音，提示音支持内置音效或导入自定义音频，提醒设置旁有常驻试听按钮、收起面板也能直接试听。完成的番茄会计入统计，也可通过事件被其他插件感知。",
    "permissions": [
      "ui",
      "tasks",
      "storage",
      "notify",
      "sound",
      "events"
    ],
    "entry": "main.js",
    "order": 4,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "weekly-report",
    "name": "周度报告",
    "version": "0.1.0",
    "author": "U-Time内置",
    "icon": "chart-column",
    "faIcon": "chart-column",
    "description": "按周汇总：每天的时间块分布、分类占比、任务完成度，一眼看清这一周过得怎么样。",
    "permissions": [
      "ui",
      "tasks",
      "blocks"
    ],
    "entry": "main.js",
    "order": 5,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "rss-reader",
    "name": "RSS 信息流",
    "version": "1.5.0",
    "author": "U-Time内置",
    "icon": "rss",
    "faIcon": "rss",
    "description": "订阅 RSS / Atom 源并聚合成一条信息流：多源并发抓取、RSS 2.0 / Atom / RDF 解析、按源与关键词过滤、未读与星标标记、顶栏一键添加源、摘要与原文正文展开、一键把带时间的条目转成U-Time提醒；粘贴网站首页还能自动发现订阅地址。抓到新内容时广播给微信推送插件，可在推送设置里单独勾选这个插件是否推送到微信。",
    "permissions": [
      "ui",
      "storage",
      "notify",
      "http",
      "openUrl",
      "tasks",
      "blocks",
      "timeParse",
      "events"
    ],
    "entry": "main.js",
    "order": 6,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "gx-news",
    "name": "竞赛消息雷达",
    "version": "0.4.0",
    "author": "U-Time内置",
    "icon": "trophy",
    "faIcon": "trophy",
    "description": "多源竞赛消息雷达：内置摩课云竞赛平台、赛氪竞赛广场、我要参赛网三家，在「源」那一排一键切换；也能粘一个网址自己添加，RSS 订阅 / JSON 数据接口 / 网页列表自动识别，添加时真抓一次并报出条目数、认不出来说明原因。关键词过滤、类型与月份筛选、已读标记、每 10 分钟自动刷新，一键把消息转成U-Time提醒（正文没写时间时按接口给的报名截止日落期）。抓到新消息时广播给微信推送插件，可在推送设置里单独勾选这个插件是否推送到微信。注：微信小程序端受 request 合法域名白名单限制，只有摩课云一个源。",
    "permissions": [
      "ui",
      "tasks",
      "blocks",
      "storage",
      "notify",
      "events",
      "http",
      "openUrl",
      "timeParse"
    ],
    "entry": "main.js",
    "order": 7,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "chaoxing-notify",
    "name": "学习通",
    "version": "2.12.2",
    "author": "基于 dsh-user/chaoxing-notify-skill v2.0.0 · U-Time适配",
    "icon": "graduation-cap",
    "faIcon": "graduation-cap",
    "description": "学习通通知与待办：使用 notice.chaoxing.com 收件箱主路径（无需旧消息接口 IP 白名单），支持账号密码或 Cookie 登录、完整通知正文、分享码查询、作业/考试截止时间识别，可一键转为 U-Time提醒；通知支持移除（本机忽略，可恢复）与「浏览器打开（带登录态）」；课程页可在「学年分组」与「开课时间总览」间切换：前者按学年分tab（默认最近学年）、学年内按完成状态三色卡片分组（红未完成/蓝正在进行/绿已完成），后者把全部学年按开课日期排成时间轴、同日合并；点击课程卡片展开该课的开课～结课时间与所属学期，并可带登录态打开该门课的课程门户；搜索框折叠为图标；待办作业分「未截止未提交 / 已逾期未提交 / 已提交但未到截止时间」三档，截止已过不再从列表里消失，并可一键移除逾期未提交列表（仅本机隐藏，可恢复），探到已提交的从未提交段摘出；作业自动探测提交状态，已提交未批改的在标题后标「正在批改」；打开时可选「自动刷新 / 节流刷新」策略（悬停按钮可查看各自适用原因），默认自动刷新；新增「通知分类」页：顶部下拉按学年筛选（按中国学年制从通知时间推导，9 月至次年 8 月），旁边一排类型胶囊（全部/通知/作业/考试/签到，计数随学年走）；顶部五个标签页均带计数（通知分类显示当前可见通知数，待办作业带逾期与已提交胶囊）；搜索支持拼音首字母缩写（bj→北京、dx→大学英语、25fh→25防火，收件箱与课程两处搜索均生效，数据表由 tools/gen-chaoxing-pinyin.js 生成，含多音字全部读音）。",
    "permissions": [
      "ui",
      "tasks",
      "blocks",
      "storage",
      "notify",
      "events",
      "http",
      "openUrl",
      "timeParse"
    ],
    "entry": "main.js",
    "order": 8,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "cppu-notify",
    "name": "警大门户通知",
    "version": "1.19.0",
    "author": "基于 dsh-user/cppu-notify-skill v1.2.1 · U-Time适配（1.19.0 一卡通自动登录与账单同步）",
    "icon": "building-columns",
    "faIcon": "building-columns",
    "description": "智慧警大门户通知：登录一次后全程自动登录——优先恢复门户票据，主 SSO 有效时自动补全 bridge 链路，票据过期则自动识别验证码完成登录。左侧「校园服务」栏内置 WebVPN、教育邮箱、教务、学生选课、学生请假、创新学分、学工、我的请假、一网通办、一卡通十个入口（默认收起，点左上角把手展开，标题与图标自动识别）。其中「学生选课」「学生请假」「创新学分」是智慧教务视图，在本插件内直接拉数据：选课任务与已选课程（标出本人自选 / 教务代选）、请假记录与可请假课次（今天 / 本周 / 本学期三档，可选课次填写请假理由并打开教务提交，也可先存成待办）、按学期汇总的创新实践学分（申请数 / 已认定数，卡片可展开查看接口返回的项目字段）；教务 SPA 没有 URL 深链，所以这三个入口开视图而不是开网页，写操作最终仍回教务确认，入口里的「去教务」会用统一身份认证会话现场换一次性票据免密直达首页。「教育邮箱」复用本插件密钥库里保存的警大密码，以 2025290058@cppu.edu.cn 自动提交登录；「我的请假」是学工 SPA 的 hash 路由直达（裸开，不走换票）；「一卡通」使用独立 OAuth 自动登录，账号、密码和令牌加密保存在本机密钥库，打开视图后自动读取平台账单并识别充值记录，可按年、月、日查看充值量与总充值量，同时保留账单、充值和账户中心应用内页面。支持每 10 分钟自动刷新、按月和考试/比赛/通知分类筛选、正文阅读、附件显示与应用内下载、转为提醒。抓到新通知时广播给微信推送插件，可在推送设置里单独勾选这个插件是否推送到微信。",
    "permissions": [
      "ui",
      "tasks",
      "blocks",
      "storage",
      "notify",
      "events",
      "http",
      "openUrl",
      "timeParse",
      "vault"
    ],
    "entry": "main.js",
    "order": 9,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "unavailable"
    }
  },
  {
    "id": "wechat-push",
    "name": "微信提醒推送",
    "version": "1.9.0",
    "author": "U-Time内置",
    "icon": "comment-dots",
    "faIcon": "comment-dots",
    "description": "通过 PushPlus（推荐）把时间块、任务截止与插件收集的新消息推送到微信；推送内容用带图标的多列下拉勾选，插件消息还能细到单个插件（学习通 / 警大门户 / 竞赛消息 / RSS / 学校通知 各勾各的）。插件消息先攒 2 分钟再合并成一条推送，兼容 PushPlus 频次限制。支持 Token、可选 Topic 群组和测试消息，内置 pushplus 官方文档入口与一键获取 Token；兼容旧版 Server酱配置。",
    "permissions": [
      "ui",
      "tasks",
      "blocks",
      "storage",
      "notify",
      "events",
      "http",
      "openUrl"
    ],
    "entry": "main.js",
    "order": 10,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "cn-holiday",
    "name": "中国节假日",
    "version": "0.3.0",
    "author": "U-Time内置 · 数据源 NateScarlet/holiday-cn",
    "icon": "calendar-day",
    "faIcon": "calendar-day",
    "description": "中国法定节假日、调休上班日和下次休息日；内置 2024–2026 离线数据，首屏不再探测未公布年份，缺失年份按需联网并缓存。",
    "permissions": [
      "ui",
      "storage",
      "notify",
      "http"
    ],
    "entry": "main.js",
    "order": 11,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "exam-calendar",
    "name": "考试日历",
    "version": "0.3.2",
    "author": "your-name",
    "icon": "calendar-check",
    "faIcon": "calendar-check",
    "description": "大学生国家级考试倒计时与全流程查看（四六级/考研/教师资格/计算机等级/专四专八/普通话）。支持按单一考试筛选报名、准考证打印、口试/笔试等流程；CET 与普通话会提示各学校/考点/省份时间可能不同，并可直达全国报名系统。普通话水平测试无全国统一考试日期，按各省分批的报名与测试窗口标注。数据在构建时由官方公告采集后内嵌。列表行按「日期+考试名」与「倒计时+操作」两行排布，窄屏下考试名不再被操作按钮挤压截断。",
    "permissions": [
      "ui",
      "tasks",
      "blocks",
      "storage",
      "notify",
      "events",
      "openUrl",
      "timeParse"
    ],
    "entry": "main.js",
    "order": 12,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "dorm-duty",
    "name": "轮换值日",
    "version": "1.3.0",
    "author": "U-Time内置",
    "icon": "broom",
    "faIcon": "broom",
    "description": "把「按成员顺序轮换」的公共事务（宿舍值日 / 公区卫生 / 打水…）集中管理：一个插件里可以放多套互相独立的轮换，各有自己的成员、周期、起始日与提醒时刻。用「起始日 + 周期」切段、一段一批人：每周轮换时整周都是同一批人，不会天天催。支持每天 / 每 3 天 / 每周 / 每两周与自定义 N 天，还可设「每轮人数」让 2 人以上一起当班（按名单顺序滑动轮转）；成员可增删、改名、上下调整轮换顺序，误删可从「已移除」恢复；某一轮临时换人（可勾选多人）只影响那一轮，撤销即回到原排班。提醒可设时刻与提示音，只在每轮第一天触发一次，当天没打开应用会在下次打开时补提醒一次；也可一键把本轮加入今日任务。标签支持右键（小程序端点标签后的「⋯」）：切组、改名、删除，或把整套轮换连成员带规则复制一份再改名，也能从别的轮换按名字导入成员。",
    "permissions": [
      "ui",
      "tasks",
      "storage",
      "notify",
      "sound"
    ],
    "entry": "main.js",
    "order": 13,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "inbox-drop",
    "name": "拖入消息收纳",
    "version": "1.0.1",
    "author": "U-Time内置",
    "icon": "inbox",
    "faIcon": "inbox",
    "description": "把散落各处的消息拖进来就收好：微信/QQ 聊天文字、通知截图、网页段落、文件都能直接拖到面板上，自动识别来源平台、消息类型与日期时间，补一个可修正的确认条后收进应用收件箱，随时一键转成任务或时间块。聊天里长按选中的消息同样支持 Ctrl+V 粘贴；截图会作为附件跟随任务。不接收可执行文件，重复消息自动去重。",
    "permissions": [
      "ui",
      "storage",
      "tasks",
      "blocks",
      "notify",
      "sound",
      "timeParse"
    ],
    "entry": "main.js",
    "order": 14,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "plugin-guide",
    "name": "插件使用说明",
    "version": "1.3.2",
    "author": "U-Time内置",
    "icon": "circle-question",
    "faIcon": "circle-question",
    "description": "按学习、效率、信息、生活与工具分类，用卡片快速查看每个内置插件的用途、使用步骤、平台支持和注意事项。",
    "permissions": [
      "ui",
      "notify",
      "openUrl"
    ],
    "entry": "main.js",
    "order": 99,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  }
];
export const BUILTIN_IDS = BUILTIN_PLUGINS.map((plugin) => plugin.id);
