// Generated by tools/sync-plugins.js; edit desktop plugin manifests then rerun the sync script.
const plugins = [
  {
    "id": "shiguang-schedule",
    "name": "课程表",
    "version": "3.8.0",
    "author": "基于 XingHeYuZhuan/shiguangschedule · Le时间管理适配",
    "icon": "calendar-days",
    "faIcon": "calendar-days",
    "description": "将时光课程表嵌入 Le 时间管理；周视图一屏显示周一到周日全部节次（默认 10 节），手机端无边距铺满整屏，视图切换与常用操作收在右上角「⋯」菜单；支持选择学校并登录教务一键导入、教务 XLSX/XLS/CSV/TSV/HTML 导入、多课表、课程管理、彩色课程块（默认开）与个性化配置、JSON/ICS 备份及时间块联动。",
    "permissions": [
      "ui",
      "storage",
      "blocks",
      "notify",
      "http",
      "events",
      "schoolImport"
    ],
    "entry": "main.js",
    "order": 1,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "unavailable"
    }
  },
  {
    "id": "web-collector",
    "name": "网页收集",
    "version": "1.2.2",
    "author": "Le时间管理内置",
    "icon": "bookmark",
    "faIcon": "bookmark",
    "description": "输入网址自动读取网站名称、favicon，并智能匹配 Font Awesome 图标；支持单独获取/更换网站图标、搜索、备注、刷新元信息和一键打开。",
    "permissions": [
      "ui",
      "storage",
      "notify",
      "http",
      "openUrl"
    ],
    "entry": "main.js",
    "order": 2,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "unavailable"
    }
  },
  {
    "id": "school-notice",
    "name": "学校通知网站",
    "version": "1.3.1",
    "author": "Le时间管理内置",
    "icon": "school",
    "faIcon": "school",
    "description": "输入学校公告/通知网址后自动识别常见高校 CMS 列表；对「服务端只吐空壳、列表靠 JS 渲染」的门户站点，命中已登记适配器时直接读取其数据接口。支持会话登录、用户名密码和手动验证码，并可把公告转成 Le时间管理提醒。站点标签页可右键弹出操作菜单（刷新 / 登录配置 / 编辑 / 打开 / 删除）。",
    "permissions": [
      "ui",
      "storage",
      "tasks",
      "blocks",
      "notify",
      "http",
      "openUrl",
      "timeParse"
    ],
    "entry": "main.js",
    "order": 3,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "unavailable"
    }
  },
  {
    "id": "pomodoro",
    "name": "番茄专注",
    "version": "0.5.1",
    "author": "Le时间管理内置",
    "icon": "hourglass-half",
    "faIcon": "hourglass-half",
    "description": "环形番茄钟：挑一个任务开始专注，25 分钟后休息。自定义时长精确到秒，分 / 秒分开填（1 分 30 秒就是 1 分 30 秒，不必再写 1.5）。专注 / 休息结束可分别设置通知与提示音，提示音支持内置音效或导入自定义音频，提醒设置旁有常驻试听按钮、收起面板也能直接试听。完成的番茄会计入统计，也可通过事件被其他插件感知。",
    "permissions": [
      "ui",
      "tasks",
      "storage",
      "notify",
      "sound",
      "events"
    ],
    "entry": "main.js",
    "order": 4,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "weekly-report",
    "name": "周度报告",
    "version": "0.1.0",
    "author": "Le时间管理内置",
    "icon": "chart-column",
    "faIcon": "chart-column",
    "description": "按周汇总：每天的时间块分布、分类占比、任务完成度，一眼看清这一周过得怎么样。",
    "permissions": [
      "ui",
      "tasks",
      "blocks"
    ],
    "entry": "main.js",
    "order": 5,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "rss-reader",
    "name": "RSS 信息流",
    "version": "1.1.0",
    "author": "Le时间管理内置",
    "icon": "rss",
    "faIcon": "rss",
    "description": "订阅 RSS / Atom 源并聚合成一条信息流：多源并发抓取、RSS 2.0 / Atom / RDF 解析、按源与关键词过滤、未读与星标标记、摘要展开、一键把带时间的条目转成Le时间管理提醒；粘贴网站首页还能自动发现订阅地址。",
    "permissions": [
      "ui",
      "storage",
      "notify",
      "http",
      "openUrl",
      "tasks",
      "blocks",
      "timeParse"
    ],
    "entry": "main.js",
    "order": 6,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "unavailable"
    }
  },
  {
    "id": "gx-news",
    "name": "竞赛消息雷达",
    "version": "0.2.0",
    "author": "Le时间管理内置",
    "icon": "trophy",
    "faIcon": "trophy",
    "description": "抓取摩课云竞赛平台（gxxsjs.com）的竞赛通知与资讯：关键词过滤、类型筛选、已读标记、自动刷新，并可一键把带时间的消息转成Le时间管理提醒。",
    "permissions": [
      "ui",
      "tasks",
      "blocks",
      "storage",
      "notify",
      "events",
      "http",
      "openUrl",
      "timeParse"
    ],
    "entry": "main.js",
    "order": 7,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "chaoxing-notify",
    "name": "学习通",
    "version": "2.12.0",
    "author": "基于 dsh-user/chaoxing-notify-skill v2.0.0 · Le时间管理适配",
    "icon": "graduation-cap",
    "faIcon": "graduation-cap",
    "description": "学习通通知与待办：使用 notice.chaoxing.com 收件箱主路径（无需旧消息接口 IP 白名单），支持账号密码或 Cookie 登录、完整通知正文、分享码查询、作业/考试截止时间识别，可一键转为 Le时间管理提醒；通知支持移除（本机忽略，可恢复）与「浏览器打开（带登录态）」；课程页按学年分tab（默认最近学年），学年内按完成状态三色卡片分组（红未完成/蓝正在进行/绿已完成），搜索框折叠为图标；待办作业自动探测提交状态，已提交未批改的在标题后标「正在批改」；打开时可选「自动刷新 / 节流刷新」策略（悬停按钮可查看各自适用原因），默认自动刷新；新增「通知分类」页：顶部下拉按学年筛选（按中国学年制从通知时间推导，9 月至次年 8 月），页内按通知/作业/考试/签到分区展示；顶部五个标签页均带计数（通知分类显示当前可见通知数）；搜索支持拼音首字母缩写（bj→北京、dx→大学英语、25fh→25防火，收件箱与课程两处搜索均生效，数据表由 tools/gen-chaoxing-pinyin.js 生成，含多音字全部读音）。",
    "permissions": [
      "ui",
      "tasks",
      "blocks",
      "storage",
      "notify",
      "events",
      "http",
      "openUrl",
      "timeParse"
    ],
    "entry": "main.js",
    "order": 8,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "cppu-notify",
    "name": "警大门户通知",
    "version": "1.10.0",
    "author": "基于 dsh-user/cppu-notify-skill v1.2.1 · Le时间管理适配（1.10.0 校园服务栏头部去重）",
    "icon": "building-columns",
    "faIcon": "building-columns",
    "description": "智慧警大门户通知：登录一次后全程自动登录——优先恢复门户票据，主 SSO 有效时自动补全 bridge 链路，票据过期则自动识别验证码完成登录。左侧「校园服务」栏内置 WebVPN、教育邮箱、教务、学工、一网通办五个入口（默认收起，点左上角把手展开，标题与图标自动识别）；「教务」用统一身份认证会话现场换一次性票据免密直达，无需手填 token。支持每 10 分钟自动刷新、按月筛选、正文阅读与转为提醒。",
    "permissions": [
      "ui",
      "tasks",
      "blocks",
      "storage",
      "notify",
      "events",
      "http",
      "openUrl",
      "timeParse",
      "vault"
    ],
    "entry": "main.js",
    "order": 9,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "unavailable"
    }
  },
  {
    "id": "wechat-push",
    "name": "微信提醒推送",
    "version": "1.8.1",
    "author": "Le时间管理内置",
    "icon": "comment-dots",
    "faIcon": "comment-dots",
    "description": "通过 PushPlus（推荐）把时间块、任务截止与插件收集的新消息推送到微信；插件消息先攒 2 分钟再合并成一条推送，兼容 PushPlus 频次限制。支持 Token、可选 Topic 群组和测试消息，内置 pushplus 官方文档入口与一键获取 Token；兼容旧版 Server酱配置。",
    "permissions": [
      "ui",
      "tasks",
      "blocks",
      "storage",
      "notify",
      "events",
      "http",
      "openUrl"
    ],
    "entry": "main.js",
    "order": 10,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "cn-holiday",
    "name": "中国节假日",
    "version": "0.3.0",
    "author": "Le时间管理内置 · 数据源 NateScarlet/holiday-cn",
    "icon": "calendar-day",
    "faIcon": "calendar-day",
    "description": "中国法定节假日、调休上班日和下次休息日；内置 2024–2026 离线数据，首屏不再探测未公布年份，缺失年份按需联网并缓存。",
    "permissions": [
      "ui",
      "storage",
      "notify",
      "http"
    ],
    "entry": "main.js",
    "order": 11,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "exam-calendar",
    "name": "考试日历",
    "version": "0.3.2",
    "author": "your-name",
    "icon": "calendar-check",
    "faIcon": "calendar-check",
    "description": "大学生国家级考试倒计时与全流程查看（四六级/考研/教师资格/计算机等级/专四专八/普通话）。支持按单一考试筛选报名、准考证打印、口试/笔试等流程；CET 与普通话会提示各学校/考点/省份时间可能不同，并可直达全国报名系统。普通话水平测试无全国统一考试日期，按各省分批的报名与测试窗口标注。数据在构建时由官方公告采集后内嵌。列表行按「日期+考试名」与「倒计时+操作」两行排布，窄屏下考试名不再被操作按钮挤压截断。",
    "permissions": [
      "ui",
      "tasks",
      "blocks",
      "storage",
      "notify",
      "events",
      "openUrl",
      "timeParse"
    ],
    "entry": "main.js",
    "order": 12,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "dorm-duty",
    "name": "轮换值日",
    "version": "1.2.0",
    "author": "Le时间管理内置",
    "icon": "broom",
    "faIcon": "broom",
    "description": "把「按成员顺序轮换」的公共事务（宿舍值日 / 公区卫生 / 打水…）集中管理：一个插件里可以放多套互相独立的轮换，各有自己的成员、周期、起始日与提醒时刻。用「起始日 + 周期」切段、一段一批人：每周轮换时整周都是同一批人，不会天天催。支持每天 / 每 3 天 / 每周 / 每两周与自定义 N 天，还可设「每轮人数」让 2 人以上一起当班（按名单顺序滑动轮转）；成员可增删、改名、上下调整轮换顺序，误删可从「已移除」恢复；某一轮临时换人（可勾选多人）只影响那一轮，撤销即回到原排班。提醒可设时刻与提示音，只在每轮第一天触发一次，当天没打开应用会在下次打开时补提醒一次；也可一键把本轮加入今日任务。",
    "permissions": [
      "ui",
      "tasks",
      "storage",
      "notify",
      "sound"
    ],
    "entry": "main.js",
    "order": 13,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "inbox-drop",
    "name": "拖入消息收纳",
    "version": "1.0.1",
    "author": "Le时间管理内置",
    "icon": "inbox",
    "faIcon": "inbox",
    "description": "把散落各处的消息拖进来就收好：微信/QQ 聊天文字、通知截图、网页段落、文件都能直接拖到面板上，自动识别来源平台、消息类型与日期时间，补一个可修正的确认条后收进应用收件箱，随时一键转成任务或时间块。聊天里长按选中的消息同样支持 Ctrl+V 粘贴；截图会作为附件跟随任务。不接收可执行文件，重复消息自动去重。",
    "permissions": [
      "ui",
      "storage",
      "tasks",
      "blocks",
      "notify",
      "sound",
      "timeParse"
    ],
    "entry": "main.js",
    "order": 14,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  },
  {
    "id": "plugin-guide",
    "name": "插件使用说明",
    "version": "1.3.1",
    "author": "Le时间管理内置",
    "icon": "circle-question",
    "faIcon": "circle-question",
    "description": "按学习、效率、信息、生活与工具分类，用卡片快速查看每个内置插件的用途、使用步骤、平台支持和注意事项。",
    "permissions": [
      "ui",
      "notify",
      "openUrl"
    ],
    "entry": "main.js",
    "order": 99,
    "platforms": {
      "windows": "full",
      "android": "full",
      "miniprogram": "native"
    }
  }
];
const byId = {};
plugins.forEach((plugin) => { byId[plugin.id] = plugin; });
module.exports = { plugins, byId };
