// Generated by tools/sync-miniprogram-models.js; do not edit.
// Source: le-time-management/public/plugins/rss-reader/main.js
// SHA256: a433e995bd66ac0c84b95ef01570b94366cbceab4d1dc9fe289bce4d788f553d
const DEFAULT_FEEDS = [
    { url: "https://sspai.com/feed", title: "少数派" },
    { url: "https://www.ruanyifeng.com/blog/atom.xml", title: "阮一峰的网络日志" },
    { url: "https://www.infoq.cn/feed", title: "InfoQ 中文" },
    { url: "https://daily.juya.uk/rss.xml", title: "橘鸦AI早报" },
  ];
  /* 一键添加的推荐源（与默认源不重叠） */
  const SUGGESTED_FEEDS = [
    { url: "https://feed.cnblogs.com/news/rss", title: "博客园新闻" },
    { url: "https://www.appinn.com/feed/", title: "小众软件" },
    { url: "https://www.ithome.com/rss/", title: "IT之家" },
    { url: "https://coolshell.cn/feed", title: "酷壳" },
  ];
  /* 源标记色：只用在 6px 圆点上，深色模式下也不会刺眼 */
  const FEED_COLORS = ["#0F4C5C", "#118AB2", "#2EC4B6", "#9B5DE5", "#E3A008", "#FF6B6B", "#5B6BE8", "#5B8F7B"];
  /* 没在 HTML 里声明 feed 时，按常见约定路径兜底试（顺序即优先级） */
  const COMMON_PATHS = ["/feed", "/rss", "/atom.xml", "/feed.xml", "/index.xml", "/rss.xml"];
  /* 条目显示样式。三档都渲染**同一个** .rss-card 容器（只加密度差异），
     因为 ui.list 的点击委托是 `closest(".rss-card")` —— 换容器类名等于把打开/收藏/提醒全弄哑。
     布局差异全部走 CSS：wrap 上挂 data-style，选择器写 .rss-wrap[data-style="compact"] …。 */
  const STYLES = ["card", "compact", "title"];
  const STYLE_LABELS = { card: "卡片", compact: "紧凑", title: "标题" };
function esc(s) {
    return String(s == null ? "" : s)
      .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;").replace(/'/g, "&#39;");
  }

  /* 实体解码。必须「一次扫描、逐个体替换」—— 分两轮（先 &amp; 再 &lt;）会把
     `&amp;lt;` 二次解码成 `<`，把用户文本里的尖括号还原出来。 */
  const NAMED_ENTITIES = {
    amp: "&", lt: "<", gt: ">", quot: '"', apos: "'", nbsp: "\u00a0",
    hellip: "…", mdash: "—", ndash: "–", ldquo: "“", rdquo: "”",
    lsquo: "‘", rsquo: "’", times: "×", middot: "·", bull: "•", copy: "©",
  };
  function decodeEntities(s) {
    return String(s == null ? "" : s).replace(/&(#[xX][0-9a-fA-F]+|#\d+|[a-zA-Z][a-zA-Z0-9]*);/g, (whole, body) => {
      if (body[0] === "#") {
        const cp = body[1] === "x" || body[1] === "X" ? parseInt(body.slice(2), 16) : parseInt(body.slice(1), 10);
        if (!Number.isFinite(cp) || cp <= 0 || cp > 0x10ffff) return whole;
        try { return String.fromCodePoint(cp); } catch (e) { return whole; }
      }
      const hit = NAMED_ENTITIES[body.toLowerCase()];
      return hit === undefined ? whole : hit;
    });
  }

  function stripCdata(s) {
    return String(s == null ? "" : s).replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, "$1");
  }

  /* 摘要 / 标题 → 纯文本：先剥 CDATA（有的源把整段 HTML 塞在里面），
     再解实体（有的源把 HTML 转义成 &lt;p&gt;），最后去标签。顺序不能反 ——
     先解实体才能把转义过的标签也去掉。

     去标签分两步，两处都有实际后果：
     · 行内标签（<a> <b> <strong>…）**删除不留空格** —— 中文里 <a> 常包住一整段，
       留空格会把「查看全文」切成「查看 全文」；
     · 其余块级标签替换成空格，避免相邻段落粘成一个词；
     · 且只认「标签名以字母开头」：`&lt;9 月 20 日&gt;` 解出来是正文不是标签，
       一刀切 /<[^>]*>/ 会把它删掉（"报名截止 ，请抓紧"）。浏览器 tokenizer 同规则。 */
  const INLINE_TAGS = "a|b|i|em|strong|span|code|small|sub|sup|u|s|mark|abbr|cite|q|kbd|samp|var|time|bdi|bdo|ruby|rt|rp|font|label|ins|del|wbr";
  function toText(raw) {
    return decodeEntities(stripCdata(raw))
      .replace(/<script[\s\S]*?<\/script>/gi, " ")
      .replace(/<style[\s\S]*?<\/style>/gi, " ")
      .replace(/<!--[\s\S]*?-->/g, " ")
      .replace(/<br\s*\/?>/gi, " ")
      .replace(/<\/p>/gi, " ")
      .replace(new RegExp("<\\/?(?:" + INLINE_TAGS + ")\\b[^>]*>", "gi"), "")
      .replace(/<\/?[a-zA-Z][^>]*>/g, " ")
      .replace(/<[!?][^>]*>/g, " ")
      .replace(/\s+/g, " ")
      .trim();
  }

  function clip(s, n) {
    const t = String(s == null ? "" : s);
    return t.length > n ? t.slice(0, n - 1) + "…" : t;
  }

  /* 路径归一：折掉 . 与 .. —— 相对 href 拼出来的 "…/blog/../2026/x.html" 是脏地址，
     存进缓存、显示在卡片里都难看，也不该指望下游替我们收拾。query / fragment 原样带过。 */
  function normalizePath(p) {
    const s = String(p == null ? "" : p);
    const cut = s.search(/[?#]/);
    const path = cut >= 0 ? s.slice(0, cut) : s;
    const tail = cut >= 0 ? s.slice(cut) : "";
    const absolute = path.startsWith("/");
    const segs = path.split("/");
    const out = [];
    for (let i = 0; i < segs.length; i++) {
      const seg = segs[i];
      if (seg === ".") continue;
      if (seg === "..") {
        // 绝对路径的 out[0] 是空串（split 的产物），不能被 pop 掉，否则会越过根
        if (out.length > (absolute ? 1 : 0) && out[out.length - 1] !== "..") out.pop();
        else if (!absolute) out.push("..");
        continue;
      }
      out.push(seg);
    }
    let res = out.join("/");
    if (absolute && !res.startsWith("/")) res = "/" + res;
    return res + tail;
  }

  /* 相对链接 → 绝对。不依赖 URL 构造器：它在插件沙箱与测试环境里未必存在，
     且失败时会抛异常。返回值保证只有 http(s) 或空串，杜绝 javascript: 之类。 */
  function absolutize(href, base) {
    const h = String(href == null ? "" : href).trim().replace(/[\r\n\t]/g, "");
    if (!h) return "";
    if (/^[a-z][a-z0-9+.-]*:/i.test(h)) return /^https?:/i.test(h) ? h : "";
    if (h.startsWith("//")) return "https:" + h;
    const b = String(base == null ? "" : base).trim();
    const m = b.match(/^(https?:\/\/[^/?#]+)([^?#]*)/i);
    if (!m) return "";
    const origin = m[1];
    const path = m[2] || "/";
    if (h.startsWith("#")) return origin + path;
    if (h.startsWith("/")) return origin + normalizePath(h);
    const dir = path.endsWith("/") ? path : path.replace(/[^/]*$/, "");
    return origin + normalizePath(dir + h);
  }

  /* 规范化用户输入的地址：允许 "sspai.com/feed" 这种省略协议的写法，
     但**非 http(s) 的 scheme 一律拒绝** —— 否则 "javascript:alert(1)" 会被
     补成 "https://javascript:alert(1)"，虽然最终打不通，也没必要把它带进存储。 */
  function normalizeFeedUrl(input) {
    let s = String(input == null ? "" : input).trim().replace(/^feed:\/\//i, "https://");
    if (!s) return "";
    if (/^[a-z][a-z0-9+.-]*:/i.test(s) && !/^https?:/i.test(s)) return "";
    if (!/^https?:\/\//i.test(s)) s = "https://" + s.replace(/^\/+/, "");
    return /^https?:\/\/[^/?#\s]+/i.test(s) ? s : "";
  }

  function hostOf(url) {
    const m = String(url || "").match(/^https?:\/\/([^/?#]+)/i);
    return m ? m[1] : "";
  }
function hashId(s) {
    let h = 2166136261;
    const t = String(s == null ? "" : s);
    for (let i = 0; i < t.length; i++) {
      h ^= t.charCodeAt(i);
      h = Math.imul(h, 16777619);
    }
    return (h >>> 0).toString(36);
  }

  /* ═══════════════ XML / RSS 解析 ═══════════════ */

  /* 取第一个匹配标签的文本内容。标签名可带命名空间前缀（content:encoded / dc:creator），
     所以前缀一律用 (?:[\w.-]+:)? 容忍。 */
  function tagText(block, names) {
    for (let i = 0; i < names.length; i++) {
      const n = names[i].replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      const re = new RegExp("<(?:[\\w.-]+:)?" + n + "\\b[^>]*>([\\s\\S]*?)<\\/(?:[\\w.-]+:)?" + n + "\\s*>", "i");
      const m = block.match(re);
      if (m) {
        const v = decodeEntities(stripCdata(m[1])).trim();
        if (v) return v;
      }
    }
    return "";
  }

  /* 从一个标签串里取属性值（属性可能用单引号、双引号或裸值）。 */
  function attrOf(tag, name) {
    const re = new RegExp("\\b" + name + "\\s*=\\s*(?:\"([^\"]*)\"|'([^']*)'|([^\\s\"'>]+))", "i");
    const m = String(tag || "").match(re);
    if (!m) return "";
    return decodeEntities(m[1] != null ? m[1] : m[2] != null ? m[2] : (m[3] || "")).trim();
  }

  /* 频道自身的站点地址。Atom 的 <feed> 里往往同时挂着 rel=self（feed 地址本身）
     和 rel=alternate（站点首页），顺序还不固定 —— 直接取第一个 link 会拿到 feed 地址，
     把「打开网站」指向 XML。和条目一样按 rel 挑。 */
  function channelLink(head) {
    const tags = String(head || "").match(/<(?:[\w.-]+:)?link\b[^>]*\/?>/gi) || [];
    let fallback = "";
    for (let i = 0; i < tags.length; i++) {
      const href = attrOf(tags[i], "href");
      if (!href) continue;
      const rel = (attrOf(tags[i], "rel") || "alternate").toLowerCase();
      if (rel === "alternate") return href;
      if (!fallback) fallback = href;
    }
    return fallback;
  }

  /* 条目链接。Atom 用 <link href>（且有 self / alternate 多个），RSS 用 <link>文本。
     优先 rel=alternate 的 href，再退到 <link> 文本，最后才看 <guid>/<id>。 */
  function itemLink(block, baseUrl) {
    const linkTags = String(block || "").match(/<(?:[\w.-]+:)?link\b[^>]*\/?>/gi) || [];
    let fallback = "";
    for (let i = 0; i < linkTags.length; i++) {
      const href = attrOf(linkTags[i], "href");
      if (!href) continue;
      const rel = (attrOf(linkTags[i], "rel") || "alternate").toLowerCase();
      if (rel === "alternate") return absolutize(href, baseUrl);
      if (!fallback) fallback = href;
    }
    if (fallback) return absolutize(fallback, baseUrl);
    const text = tagText(block, ["link"]);
    if (text) return absolutize(text, baseUrl);
    const guid = tagText(block, ["guid", "id"]);
    if (/^https?:\/\//i.test(guid)) return guid;
    return "";
  }

  /* 作者。Atom 是 <author><name>阮一峰</name><uri>…</uri></author>，
     直接取 <author> 的文本会把 uri 一起吞进来（"阮一峰 http://…"），
     所以要先钻进 <name>。RSS 2.0 则走 <dc:creator> 或 <author> 纯文本。 */
  function itemAuthor(block) {
    const direct = toText(tagText(block, ["dc:creator", "creator"]));
    if (direct) return direct;
    const holder = String(block || "").match(/<(?:[\w.-]+:)?author\b[^>]*>([\s\S]*?)<\/(?:[\w.-]+:)?author\s*>/i);
    if (holder) {
      const inner = toText(tagText(holder[1], ["name"])) || toText(holder[1]);
      if (inner) return inner;
    }
    return toText(tagText(block, ["name"]));
  }

  function itemCover(block, baseUrl) {
    const enc = String(block || "").match(/<(?:[\w.-]+:)?enclosure\b[^>]*>/i);
    if (enc) {
      const url = attrOf(enc[0], "url");
      const type = attrOf(enc[0], "type").toLowerCase();
      if (url && (type.startsWith("image") || /\.(jpe?g|png|gif|webp|avif)(\?|$)/i.test(url))) return absolutize(url, baseUrl);
    }
    const media = String(block || "").match(/<(?:[\w.-]+:)?(?:content|thumbnail|image)\b[^>]*>/gi) || [];
    for (let i = 0; i < media.length; i++) {
      const url = attrOf(media[i], "url");
      if (url && /\.(jpe?g|png|gif|webp|avif)(\?|$)/i.test(url)) return absolutize(url, baseUrl);
    }
    const body = block.match(/<(?:[\w.-]+:)?(?:description|summary|content)\b[^>]*>([\s\S]*?)<\/(?:[\w.-]+:)?(?:description|summary|content)\s*>/i);
    if (body) {
      const img = decodeEntities(stripCdata(body[1])).match(/<img[^>]+src\s*=\s*(?:"([^"]+)"|'([^']+)')/i);
      if (img) return absolutize(img[1] || img[2], baseUrl);
    }
    return "";
  }

  /* 日期归一化成「YYYY-MM-DD HH:mm」本地时间串 —— 排序与显示共用一种形态。
     认不出来的返回空串（条目仍然展示，只是排在「时间未知」组）。 */
  function parseDateAny(raw) {
    const t = String(raw == null ? "" : raw).trim();
    if (!t) return "";
    const viaDate = new Date(t);
    if (!Number.isNaN(viaDate.getTime()) && sane(viaDate)) return toLocal(viaDate);
    // 兜底：Date 构造函数吃不下的写法（"2026-09-18 08:17:34"、"2026/09/18 08:17"）
    const m = t.match(/(\d{4})[-/年](\d{1,2})[-/月](\d{1,2})[日]?(?:[T\s]+(\d{1,2}):(\d{2})(?::(\d{2}))?)?/);
    if (m) {
      const d = new Date(Number(m[1]), Number(m[2]) - 1, Number(m[3]), Number(m[4] || 0), Number(m[5] || 0), Number(m[6] || 0));
      if (!Number.isNaN(d.getTime()) && sane(d)) return toLocal(d);
    }
    return "";
  }
  function sane(d) {
    const y = d.getFullYear();
    return y >= 1990 && y <= 2100;
  }
  function toLocal(d) {
    const p = (n) => String(n).padStart(2, "0");
    return d.getFullYear() + "-" + p(d.getMonth() + 1) + "-" + p(d.getDate()) + " " + p(d.getHours()) + ":" + p(d.getMinutes());
  }

  function looksLikeFeed(body) {
    const head = String(body || "").slice(0, 2000);
    return /<rss[\s>]|<feed[\s>]|<rdf:rdf[\s>]|<channel[\s>]/i.test(head);
  }
  function looksLikeHtml(body) {
    const head = String(body || "").slice(0, 600).trimStart();
    return /^<(!doctype\s+html|html[\s>])/i.test(head);
  }

  /* 从站点 HTML 里找声明的订阅地址（<link rel="alternate" type="application/rss+xml">）。
     返回候选数组，按 rss+xml > atom+xml > 其他 xml 排序 —— 有的站同时挂两个。 */
  function discoverFeedUrls(html, baseUrl) {
    const tags = String(html || "").match(/<link\b[^>]*>/gi) || [];
    const rss = [], atom = [], other = [];
    for (let i = 0; i < tags.length; i++) {
      const rel = (attrOf(tags[i], "rel") || "").toLowerCase();
      if (!rel.split(/\s+/).includes("alternate")) continue;
      const type = (attrOf(tags[i], "type") || "").toLowerCase();
      const href = attrOf(tags[i], "href");
      if (!href) continue;
      const abs = absolutize(href, baseUrl);
      if (!abs) continue;
      if (/rss\+xml/.test(type)) rss.push(abs);
      else if (/atom\+xml/.test(type)) atom.push(abs);
      else if (/xml/.test(type)) other.push(abs);
    }
    return [...new Set([...rss, ...atom, ...other])];
  }

  /* 解析一份 feed。返回 { title, site, items }；items 里的字段已全部清洗过。
     任何字段缺失都不抛错 —— 只有「整份不是 feed」才返回 null。 */
  function parseFeed(body, baseUrl) {
    const xml = String(body == null ? "" : body).replace(/^\uFEFF/, "");
    if (!looksLikeFeed(xml)) return null;

    // 频道头 = 第一个 item/entry 之前的片段（channel / feed 元信息都在那里）
    const firstItem = xml.search(/<(?:[\w.-]+:)?(?:item|entry)\b/i);
    const head = firstItem >= 0 ? xml.slice(0, firstItem) : xml;
    const site = tagText(head, ["link"]) || channelLink(head);
    const title = toText(tagText(head, ["title"]));

    const blocks = [];
    const re = /<(?:[\w.-]+:)?(item|entry)\b[^>]*>([\s\S]*?)<\/(?:[\w.-]+:)?\1\s*>/gi;
    let m;
    while ((m = re.exec(xml))) blocks.push(m[2]);

    const items = [];
    for (let i = 0; i < blocks.length; i++) {
      const block = blocks[i];
      const link = itemLink(block, baseUrl) || absolutize(site, baseUrl);
      const rawTitle = toText(tagText(block, ["title"]));
      const desc = tagText(block, ["description", "summary", "content:encoded", "content"]);
      const snippet = clip(toText(desc), 220);
      const author = itemAuthor(block);
      const date = parseDateAny(tagText(block, ["pubDate", "published", "updated", "dc:date", "date", "lastBuildDate"]));
      const guid = tagText(block, ["guid", "id"]);
      if (!link && !rawTitle) continue; // 空壳条目（有的源会留占位）直接丢
      items.push({
        key: guid || link || rawTitle,
        title: rawTitle || "(无标题)",
        link,
        date,
        author: clip(author, 40),
        snippet,
        cover: itemCover(block, baseUrl),
      });
    }
    return { title, site: absolutize(site, baseUrl) || baseUrl, items };
  }
module.exports = { DEFAULT_FEEDS, SUGGESTED_FEEDS, FEED_COLORS, normalizeFeedUrl, absolutize, hostOf, hashId, parseFeed, parseDateAny, toText, discoverFeedUrls, looksLikeFeed };
